name: Docker CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. TEST PHASE (Build the test stage)
      - name: Run Unit Tests
        run: |
          docker build --target test-stage -t backend-test ./backend

      # 2. LOGIN (Only if tests pass)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. BUILD PRODUCTION (Target the production stage)
      - name: Build Production Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          target: production
          load: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-backend:latest

      # 4. SECURITY SCAN
      - name: Security Scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/node-backend:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'

      # 5. PUSH (Only if everything above passed)
      - name: Push to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-backend:latest
